apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "users-portal"
  description: "A website for managing users."
  annotations:
    github.com/project-slug: Staffing-HQ/users-portal
    backstage.io/techdocs-ref: dir:.
  tags:
    - nextjs
    - react
    - ssr
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/executive"
